### ISSUE TITLE
register page detail errors

### ISSUE THREAD

**Issue by garrykevin-ep** [garrykevin-ep/Skillet#15]

**Comment by Devinwon** [comment]
how to run your project Skillet？I tried many times,but failed,

**Comment by garrykevin-ep** [comment]
python manage.py migrate
python manage.py runserver

and i have not made a stable release yet

**Comment by Devinwon** [comment]
Hi~~~, I  have fixed some errors on my pc,So I can run it now ,I also can registe an new  account. when I take the test, I got an error like this.
![error](https://user-images.githubusercontent.com/20663923/34906534-60bc7eaa-f8aa-11e7-86c2-53709eff28e3.png),and located there
![l](https://user-images.githubusercontent.com/20663923/34906593-75d5ca5c-f8ab-11e7-8427-c2307c6a0ad1.png)
,I read some codes,But....
Thanks for you help!

**Comment by Devinwon** [comment]
No questions caused the error,is it?
Thus what's the format of the question,Can you give me a example?TKS

**Comment by garrykevin-ep** [comment]
go to /admin. Login in to django admin and add questions
